models/__init__.py
from .post import Post
from .posts_tags import PostsTags
from .tag import Tag
from .user import User
from .database import db, db_add_obj

__all__ = (
    'db',
    'Post',
    'Tag',
    'PostsTags',
    'User',
    'PostsTags',
    'db_add_obj'
)

models/database.py
import logging

from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.exc import IntegrityError
from werkzeug.exceptions import BadRequest

db = SQLAlchemy()

log = logging.getLogger(__name__)


def db_add_obj(database: SQLAlchemy, obj: db.Model) -> None:
    database.session.add(obj)
    try:
        database.session.commit()
    except IntegrityError:
        log.exception(f"Could not add {obj.__class__.__name__} {obj}")
        database.session.rollback()
        raise BadRequest(f"Could not save {obj.__class__.__name__}")


__all__ = (
    'db',
    'db_add_obj',
)

models/post.py
from .database import db


class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    content = db.Column(db.Text, nullable=False)

    def __str__(self):
        return f"{self.__class__.__name__}(id={self.id}, title={self.title!r})"

    def __repr__(self):
        return str(self)

models/posts_tags.py
from .database import db


class PostsTags(db.Model):
    # __tablename__ = 'posts_tags'
    post_id = db.Column(
        db.Integer, db.ForeignKey('posts.id'), primary_key=True
    )
    tag_id = db.Column(
        db.Integer, db.ForeignKey('tags.id'), primary_key=True
    )

models/tag.py
from .database import db


class Tag(db.Model):
    __tablename__ = 'tags'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30), unique=True, nullable=False)

models/user.py
from .database import db
from flask_login import UserMixin


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30))
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    posts = db.relationship('Post', backref='author')

    def __str__(self):
        return f'{self.__class__.__name__}(name={self.name!r})'

    def __repr__(self):
        return str(self)

app.py
from os import getenv

from flask import Flask, url_for, redirect, render_template
from flask_login import LoginManager, login_required, current_user
from flask_migrate import Migrate

from models import db, User
from views.auth import auth_app
from views.posts import posts_app

app = Flask(__name__)
CONFIG_NAME = getenv("CONFIG", "DevelopmentConfig")
app.config.from_object(f"config.{CONFIG_NAME}")

app.register_blueprint(posts_app, url_prefix="/posts")
app.register_blueprint(auth_app, url_prefix="/auth")

db.init_app(app)
migrate = Migrate(app, db)

login_manager = LoginManager()
login_manager.login_view = 'auth_app.login'
login_manager.init_app(app)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


@app.cli.command('create-schemas', help='Creates all known schemas')
def create_all_schemas():
    print('create all tables...')
    db.create_all()
    print('created all tables!')


@app.cli.command('drop-schemas', help='Drop all known schemas')
def drop_all_schemas():
    print('drop all tables...')
    db.drop_all()
    print('dropped all tables!')


@app.route("/")
def posts_list():
    url_posts = url_for("posts_app.list")
    return redirect(url_posts)


@app.route("/profile/", endpoint="profile")
@login_required
def profile():
    return render_template('auth/profile.html', name=current_user.name)


if __name__ == '__main__':
    app.run()

main.py
from app import app

__all__ = (
    "app",
)

views/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user

from models import User, db, db_add_obj

auth_app = Blueprint('auth_app', __name__)


@auth_app.route("/login/", endpoint='login')
def login():
    return render_template('auth/login.html')


@auth_app.route('/login/', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')

    user = User.query.filter_by(email=email).first()

    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth_app.login'))

    login_user(user, remember=True)
    return redirect(url_for('profile'))


@auth_app.route("/signup/", endpoint='signup')
def signup():
    return render_template('auth/signup.html')


@auth_app.route("/signup/", methods=['POST'])
def signup_post():
    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')

    user = User.query.filter_by(email=email).first()

    if user:
        flash('Email address already exists')
        return redirect(url_for('auth_app.signup'))

    new_user = User(
        email=email,
        name=name,
        password=generate_password_hash(password, method='sha256')
    )
    db_add_obj(db, new_user)

    return redirect(url_for('auth_app.login'))


@auth_app.route("/logout/", endpoint='logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('posts_app.list'))

views/posts.py
import logging
from typing import List

from flask import Blueprint, render_template, request, url_for, flash, redirect
from flask_login import login_required, current_user

from models import Post, db, Tag, PostsTags, User, db_add_obj

log = logging.getLogger(__name__)

posts_app = Blueprint('posts_app', __name__)


@posts_app.get("/", endpoint='list')
def list_posts():
    posts: List[Post] = Post.query.all()
    return render_template('posts/list.html', posts=posts)


@posts_app.route("/<int:post_id>", methods=['GET', 'POST'], endpoint='details')
def get_post(post_id):
    if request.method == 'GET':
        post = Post.query.get_or_404(post_id)
        user = User.query.get_or_404(post.user_id)

        query = db.session.query(Post, Tag, PostsTags)
        query = query.join(PostsTags, PostsTags.post_id == Post.id)
        query = query.join(Tag, Tag.id == PostsTags.tag_id)
        records = query.filter(Post.id == post_id).all()

        tags = list()
        for _, tag, _ in records:
            tags.append(tag.name)

        return render_template(
            'posts/details.html',
            post=post,
            tags=tags,
            author=user,
        )

    if request.method == 'POST':
        existing_tags = [tag.name for tag in Tag.query.all()]
        requested_tags = request.form.get('tags').split()

        for name in requested_tags:
            if name in existing_tags:
                continue

            tag = Tag(name=name)
            db_add_obj(db, tag)

        existing_tags = Tag.query.all()
        for name in requested_tags:
            for tag in existing_tags:
                if tag.name == name:
                    posts_tags = PostsTags(post_id=post_id, tag_id=tag.id)
                    db_add_obj(db, posts_tags)

        post = Post.query.get_or_404(post_id)
        url_post = url_for(
            "posts_app.details",
            post_id=post.id,
            post_title=post.title,
            post_content=post.content,
        )
        return redirect(url_post)


@posts_app.route("/add/", methods=['GET', 'POST'], endpoint='add')
@login_required
def add_post():
    if request.method == 'GET':
        return render_template('posts/add.html')

    if request.method == 'POST':
        user = User.query.filter_by(id=current_user.id).first()

        title = request.form.get('title')
        content = request.form.get('content')

        post = Post(
            title=title,
            user_id=user.id,
            content=content,
        )
        db_add_obj(db, post)

        url_post = url_for("posts_app.details", post_id=post.id)
        flash(f"Created post {title}!")

        return redirect(url_post)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Base Title
        {% endblock %}
    </title>
</head>
<body style="margin: 5rem">
{% block navbar %}
    <a href="{{ url_for('posts_app.list') }}">
        Home
    </a>
    {% if current_user.is_authenticated %}
    <a href="{{ url_for('profile') }}">
        Profile
    </a>
    {% endif %}
    {% if not current_user.is_authenticated %}
        <a href="{{ url_for('auth_app.login') }}">
            Login
        </a>
        <a href="{{ url_for('auth_app.signup') }}">
            Sign Up
        </a>
    {% endif %}
    {% if current_user.is_authenticated %}
    <a href="{{ url_for('auth_app.logout') }}">
        Logout
    </a>
    {% endif %}
    <hr>
{% endblock %}

{% block body %}
Base Block
{% endblock %}
</body>
<footer style="margin-top: 1rem">
    <hr>
    <a href="mailto:feedback@awesomeanimalblog.ru">
        Feedback: feedback@awesomeanimalblog.ru
    </a>
</footer>
</html>

templates/posts/add.html
{% extends 'base.html' %}

{% block title %}
Add post
{% endblock %}

{% block body %}
    <h1>Add post</h1>

    <form method="POST">
        <div>
            <label>Title: <input type="text" name="title" required></label>
        </div>
        <div>
            <label>Content: <input type="text" name="content" required></label>
        </div>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

templates/posts/details.html
{% extends 'base.html' %}

{% block title %}
  {{ post.title }}
{% endblock %}

{% block body %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }} </li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    <h1>{{ post.title }}</h1>
    <p>Author: {{ author.name }}#{{ author.id }}</p>
    <p> {{ post.content }} </p>
    <hr>
    {% if tags %}
        <p>Tags:</p>
        <ul>
        {% for tag in tags %}
            <li>{{ tag }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    <form method="post">
        <div>
            <label>Add tags: <input type="text" name="tags" placeholder="whitespace delimiter" required></label>
            <input type="submit" value="Submit">
        </div>
    </form>
{% endblock %}

templates/posts/list.html
{% extends 'base.html' %}

{% block title %}
Posts
{% endblock %}

{% block body %}
    <h1>Posts</h1>
    <ul>
    {% for post in posts %}
        <li>
            <a href="{{ url_for('posts_app.details', post_id=post.id) }}">
                {{ post.title }}#{{ post.id }}
            </a>
        </li>
    {% else %}
        <li><em>No posts found.</em></li>
    {% endfor %}
    </ul>
    <a href="{{ url_for('posts_app.add') }}">Add post</a>
{% endblock %}